title: Open Science Symposium 2023
preposition: ''
description: >-
  The Fourth Carnegie Mellon University Open Science Symposium
baseurl: "/OSS" # the subpath of your site, e.g. /blog
url: "cmu-lib.github.io" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:

  # Language
  lang: en

  # Navigation bar
  navigation:
    logo:
      name: Carnegie Mellon University
      # img: 'cmu-logo-stacked-r.png'
      url: 'https://www.cmu.edu/'
    links:
      #- name: Program
      #  relative_url: /program/
      #- name: Talks
      #  relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Location
        relative_url: /location/
      - name: Code of Conduct
        relative_url: /code_of_conduct/
      - name: Previous Editions
        menu:
          - name: 2020
            absolute_url: 'https://events.library.cmu.edu/oss2020/'
          #- name: 2019
          #  relative_url: /2019/
          #- name: 2018
          #  relative_url: /2018/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Speakers
        relative_url: /speakers/
      - name: Virtual event information
        relative_url: /location/
      - name: Registration
        disabled: true
        absolute_url: ''
      - name: Code of Conduct
        relative_url: /code_of_conduct/

  # Information boxes
  info_bars:
    - title: Welcome to the Open Science Symposium 2023 site!
      color: primary
      main_only: true
      text: |
        This website is currently under construction. Please come back for more information later this summer!

        ---

        In the meantime, check out our last [Open Science Symposium](https://events.library.cmu.edu/oss2020/) and how CMU Libraries is supporting open science at our [Open Science & Data Collaborations website](https://www.library.cmu.edu/services/open-science#).

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: 47.37808, 8.53935
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: New Models for Research
        color: primary
      - name: Open Resources for Communities
        color: secondary
      - name: Roles of Institutions and Government
        color: info
      - name: Publishing
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: false

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true

plugins_dir: jekyll-include-cache

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"
